mrastgar/mrastgar/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls')),
]

web/urls.py
from django.urls import path
from . import views
app_name= "web"
urlpatterns = [
     path('',views.home_list, name='list'),
    path('<slug>',views.weblink, name='detail'),
    path('m001/',views.m001,name='login'),

]

web/models.py
from django.db import models

# Create your models here.
class Web(models.Model):
    title =  models.CharField(max_length =100)
    slug = models.SlugField()
    body= models.TextField()
    date= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:50]

web/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models

# Create your views here.
def home_list (request):
    web = models.Web.objects.all().order_by('date')
    arge = {'web':web}
    return render(request , 'web/home.html',arge)


def weblink(request,slug):
    web = models.Web.objects.get(slug=slug)
    return render(request, 'web/web_details.html',{'web':web})
def m001(request):
    return render(request, 'web/m001.html')

web/templates/web/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <style type="text/css">
    #myID {
      text-decoration: none;
    }
    </style>
    <meta charset="utf-8">
    <title></title>

  </head>
  <body>
    <ul>
      <a href="#" style="background:#f19800;"><i class="ion-ios-home"></i></a>
      <a href="#"><i class="ion-heart"></i></a>
      <a href="#"><i class="ion-search"></i></a>
    </ul>
    <div class="web">
      {% for web in web %}
      <h1 dir="rtl" aligh="right" ><a id="myID" href= "{% url 'web:detail' slug=web.slug %}"><font color="black"><tt>{{web.title}}</tt></font></a></h1>
      <hr/ color=blue>
      <p  dir="rtl" aligh="right">{{web.date}}</p>
      <hr/>
      {% endfor%}
      <br>
    <h3 ><a id="myID" href="#"><tt> لیست کامل</tt></a></h3>

      <hr>
      <p  dir="rtl" aligh="right">:) امیدوارم  از این قسمت ها هم خوشتون بیاد.</p>
      <h3 dir="rtl" aligh="right"><a id="myID" href="#"><tt> حمایت مالی</tt></a></h3>
      <h3 dir="rtl" aligh="right"><a id="myID" href="http://google/aparat.com"><tt>اپارات</tt></a></h3>
      <h3 dir="rtl" aligh="right"><a id="myID" href="#"><tt> تلگرام</tt></a></h3>
      <h3 dir="rtl" aligh="right"><a id="myID" href="#"><tt>یوتیوب</tt></a></h3>
      <h3 dir="rtl" aligh="right"><a id="myID" href="#"><tt>اینستاگرام</tt></a></h3>
      <br>
      <hr>
      <br>
      <h4  dir="rtl" aligh="right">پروژه ها</h4>
      <hr/ size=3 color=blue>
      <h4 dir="rtl" aligh="right"><a id="myID" href="">riuyrifis<a></h4>
      <hr>
      <br>
      <h4 dir="rtl" aligh="right" >برچسب ها</h4>
      <hr/ color=blue size=3>
      <hr/ color=blue size=3>
      <br>
    </div>

  </body>
</html>

web/templates/web/web_details.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="web-detail">
      <div class="web">
       <h4 dir="rtl" aligh="right">{{web.title}}</h4>
      <p dir="rtl" aligh="right">{{web.body}}</p>
      </div>

    </div>

  </body>
</html>